### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by kevthehermit** [carbonblack/binee#1] opened 2019-08-12 00:27 UTC
Followed steps as per the build guide. 
Copied all dll files from a windows 10 sys32 into the correct place.

There were no test files in the repo so dropped in calc.exe and tried to run against that

```
root@bae5a0b3b375:/bineedev/go/src/binee# ./binee ../../../calc.exe
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
binee/pefile.(*PeFile).readImports(0xc0000e4000)
	/bineedev/go/src/binee/pefile/pefile.go:640 +0xbbe
binee/pefile.LoadPeFile(0x7ffebeb925c7, 0x20, 0x0, 0x0, 0x0)
	/bineedev/go/src/binee/pefile/pefile.go:325 +0x1f07
binee/windows.New(0x7ffebeb925c7, 0x20, 0x4, 0x4, 0xc000058610, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/bineedev/go/src/binee/windows/winemulator.go:283 +0x20b1
main.main()
	/bineedev/go/src/binee/main.go:176 +0x604

```

**Comment by kgwinnup-cb** [comment] 2019-08-12 14:39
Hi! Thank for submitting the first issue! 

First, I forgot to upload the tests/ directory. This has been pushed into master now and you should be able to git pull the updated content. Second, is the parsing of the calc.exe. I'll explore this and see what the issue is with the parser. I know there is another issue with parsing Golang compiled exe's.

One note, Binee's tries to mock out as much as possible. Some functions are "NOP'd" out meaning they simply return to the calling function with what would be an indication of a successful call. This is particularly important for GUI APIs; these are all "NOP'd" out.

**Comment by kgwinnup** [comment] 2019-08-13 18:19
I think I have fixed this issue in a waiting PR. Output is not as complete as other samples however.

```
go build && ./binee ~/Desktop/calc.exe
[1] 0x244970b0: F GetSystemTimeAsFileTime(lpSystemTimeAsFileTime = 0xb7feffe4) = 0xb7feffe4
[1] 0x2449e8d0: P GetCurrentProcessId() = 0x0
[1] 0x2011ef30: P GetCurrentProcessId() = 0x0
[1] 0x24490b40: P GetCurrentThreadId() = 0x1001
[1] 0x2449ded0: F GetTickCount() = 0x5d52ff24
[1] 0x24490b50: F QueryPerformanceCounter(lpPerformanceCount = 0xb7feffec) = 0x1
[1] 0x20127260: F GetStartupInfoW(lpStartupInfo = 0xb7feff90) = 0xb7feff90
[1] 0x20102370: F GetModuleHandleW(lpModuleName = '') = 0x400000
[1] 0x2ad4d700: P __set_app_type(appType = 0x2) = 0x2
[1] 0x20102370: F GetModuleHandleW(lpModuleName = '') = 0x400000
[1] 0x2ad2bf30: F __p__fmode(mode = 0x401b44) = 0x4000
[1] 0x2ad2bee0: F __p__commode(mode = 0x401b44) = 0x4000
[1] 0x2ad8fcd0: P _controlfp(unNew = 0x10000, unMask = 0x30000) = 0x0
[1] 0x2449aef0: F SetUnhandledExceptionFilter(lpTopLevelExceptionFilter = 0x401b70) = 0x4
[1] 0x2ad5c520: F _initterm(PVPV = 0x4010a8, PVPV = 0x4010b0) = 0x0```

**Comment by kevthehermit** [comment] 2019-08-14 12:34
Thanks, Testing with the test samples I get up and running, there is another issue with case sensitivity on Linux, but will raise as a new issue as its not directly related.

**Comment by kgwinnup** [comment] 2019-08-14 13:46
cool, going to close this issue then.

**Comment by duzvik** [comment] 2019-08-15 10:30
Trying to mock win(dll's copied) and run test binary.

root@abeecf18bc59:~/go/src/binee# ./binee tests/ConsoleApplication1_x86.exe
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
binee/pefile.(*PeFile).readImports(0xc0000e0300)
	/bineedev/go/src/binee/pefile/pefile.go:662 +0xbf9
binee/pefile.LoadPeFile(0xc00007a480, 0x2a, 0x3, 0x5e6188, 0xc)
	/bineedev/go/src/binee/pefile/pefile.go:340 +0x2136
binee/windows.retrieveDllFromDisk(0xc0000d2ec8, 0xc0000e0100, 0xc000076a80, 0x3, 0x3, 0x5e6188, 0xc)
	/bineedev/go/src/binee/windows/loader.go:407 +0x353
binee/windows.(*WinEmulator).initPe(0xc0000c0900, 0xc0000e0000, 0x7ffd7561dee5, 0x21, 0x4, 0x4, 0xc000072600, 0x1, 0x1, 0x400, ...)
	/bineedev/go/src/binee/windows/loader.go:772 +0x357
binee/windows.New(0x7ffd7561dee5, 0x21, 0x4, 0x4, 0xc000072600, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
	/bineedev/go/src/binee/windows/winemulator.go:284 +0x2133
main.main()
	/bineedev/go/src/binee/main.go:176 +0x604

**Comment by kgwinnup** [comment] 2019-08-15 18:00
that's an interesting one. It looks like it is failing during loading of libraries, are the DLLs used from Win(7|10) 32bit?

**Comment by duzvik** [comment] 2019-08-16 09:30
I forget about 32/62 bits and I've used 64 dlls.  
So error "panic: runtime error: slice bounds out of range" was related to wrong dlls.

I've uploaded Win7 32 bit dlls and  now got this: 

root@540f0c05de29:~/go/src/binee# ./binee  tests/ConsoleApplication1_x86.exe
[1] 0x205a1fde: F GetSystemTimeAsFileTime(lpSystemTimeAsFileTime = 0xb7feffe0) = 0xb7feffe0
[1] 0x2059ab80: P GetCurrentThreadId() = 0x0
**Invalid Fetch: addresss = 0xdce6779, size = 0x1, value = 0x0**

Any ideas?

**Comment by kgwinnup** [comment] 2019-08-16 12:57
what is your mock file system root directory? I am thinking you may have to pass in a config file with it specified (I will make this a -r flag soon). For now though, if you just make a `win7.yaml` file and put this line in it: `root: "os/win10_32/"` where the root points to your win7 mock file system. Let me know if that works. By default binee will look for `./os/win10_32/` as the root.

**Comment by duzvik** [comment] 2019-08-19 10:50
> what is your mock file system root directory? 

```
root@3c67f6800f43:~/go/src/binee/os# ls -R
.:
win10_32

./win10_32:
windows

./win10_32/windows:
system32

./win10_32/windows/system32:
advapi32.dll  apisetschema.dll	kernel32.dll  kernelbase.dll  netapi32.dll  ntdll.dll  shell32.dll  urlmon.dll	user32.dll  vcruntime140.dll  wininet.dll

root@9df19463d183:~/go/src/binee/os/win10_32/windows/system32# md5sum *
95e2376b3323f062eb562b8586d0f14a  advapi32.dll
2f03490092c032392fb6ff635222b9b2  apisetschema.dll
5553784d774ca845380650e010bbda2c  kernel32.dll
aa7e805af3f7db2da9ea350423e87dfd  kernelbase.dll
8ce1a6d16b9077e91e192499eb611c5f  netapi32.dll
ed60c95c805dbaee92c90c3ab930085a  ntdll.dll
16ab4bd2acc52109f43739bf0e89e18f  shell32.dll
ebb431c6332107651cd2e2715a707994  urlmon.dll
f1dd3acaee5e6b4bbc69bc6df75cef66  user32.dll
fd0ca40f7f1c980df3e3c9c926841d98  vcruntime140.dll
44214c94911c7cfb1d52cb64d5e8368d  wininet.dll

```

win.yaml
```
root@3c67f6800f43:~/go/src/binee# cat config/win.yaml
root: "os/win10_32/"
code_page_identifier: 0x4e4
registry:
    HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\PINF: ""
    HKEY_CURRENT_USER\Software\AutoIt v3\AutoIt\Include: "yep"
    HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Arbiters\InaccessibleRange\Psi: "PhysicalAddress"
    HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Arbiters\InaccessibleRange\Root: "PhysicalAddress"
    HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\Arbiters\InaccessibleRange\PhysicalAddress: "hex(a):48,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,01,00,00,00,00,00,00,00,01,00,00,00,00,03,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,00,01,00,ff,ff,ff,ff,ff,ff,ff,ff"
```


> just make a win7.yaml file and put this line in it: root: "os/win10_32/" where the root points to your win7 mock file system

same error

**Comment by evandrix** [comment] 2019-08-28 09:22
i've encountered the same error on Windows 10 v1809 x64 (due to the lack of the Windows 32-bit DLLs i'm guessing), reproduced below for reference:

```
C:\Users\User\Desktop>binee ConsoleApplication1_x86.exe
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/carbonblack/binee/pefile.(*PeFile).readImports(0xc000094000)
        C:/Users/User/go/src/github.com/carbonblack/binee/pefile/pefile.go:662 +0xc03
github.com/carbonblack/binee/pefile.LoadPeFile(0xc00014c1c0, 0x20, 0x3, 0x60ddac, 0xc)
        C:/Users/User/go/src/github.com/carbonblack/binee/pefile/pefile.go:340 +0x1b8e
github.com/carbonblack/binee/windows.retrieveDllFromDisk(0xc00005f048, 0xc000094200, 0xc00004cd20, 0x3, 0x3, 0x60ddac, 0xc)
        C:/Users/User/go/src/github.com/carbonblack/binee/windows/loader.go:407 +0x34f
github.com/carbonblack/binee/windows.(*WinEmulator).initPe(0xc000084900, 0xc000094100, 0xc00000c3e0, 0x1b, 0x4, 0x4, 0xc0000345e0, 0x1, 0x1, 0x606700, ...)
        C:/Users/User/go/src/github.com/carbonblack/binee/windows/loader.go:772 +0x361
github.com/carbonblack/binee/windows.New(0xc00000c3e0, 0x1b, 0x4, 0x4, 0xc0000345e0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        C:/Users/User/go/src/github.com/carbonblack/binee/windows/winemulator.go:284 +0x22bf
main.main()
        C:/Users/User/go/src/github.com/carbonblack/binee/main.go:176 +0x5fa
```

so, any possibility to include a [ConsoleApplication1_x64.exe](ConsoleApplication1_x64.exe)?

**Comment by kgwinnup** [comment] 2019-08-29 02:22
Currently, we don't support x64. This is something we do have a plan for and many hooks and functionality are x64 ready (see various if `emu.PtrSize == 4|8` laying around). PE parser and loader obviously need some tweaking still for full x64 support

**Comment by evandrix** [comment] 2019-08-29 02:54
> Currently, we don't support x64. This is something we do have a plan for and many hooks and functionality are x64 ready (see various if `emu.PtrSize == 4|8` laying around). PE parser and loader obviously need some tweaking still for full x64 support

ohhh, no wonder...been banging my head against the wall for nothing :/

**Comment by knightsc** [comment] 2019-11-22 16:46
@kgwinnup I think this issue can be closed again.

**Closed as completed** 2019-11-22 16:58 UTC
